# The URL the site will be built for
base_url = "https://jessidhia.github.io"

title = "Jessidhia"
description = "Maybe I'll write about things..."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = 'hyde'

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
hyde_reverse = false
hyde_theme = "theme-base-0e"
hyde_links = [
  { name = "GitHub", url = "https://github.com/Jessidhia" },

  { name = "Twitter", url = "https://twitter.com/@jessidhia" },
]
